"""
Orchestrator: turn a completed PyPort run's SQLite database into economic
KPIs, without touching the simulation itself.

Typical use: run PyPort as usual (main.py or your own scenario script) to
produce a .db file, then run this against it:

    python -m economics.run_economics --db path/to/run.db \\
        --grid-source Funchal --tariff-json economics/tariff_profiles/tariff_period_III.json

This is a first working skeleton: it computes grid energy cost per
timestep for one scenario run, and writes the results back into the SAME
database as new metric rows (via register_economic_metrics), tagged to a
new source "economics_layer" - so PyPort's own tables/rows are never
edited, only added to.
"""

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import List, Tuple

from database import DatabaseManager

from .metrics import register_economic_metrics


def load_tariff_price_fn(tariff_json_path: str):
    """
    Load a PyPort-format tariff JSON and return a timestamp -> EUR/kWh
    function, replicating Port.get_tariff_price()'s exact lookup algorithm
    (weekday + 15-minute rounding) WITHOUT importing/instantiating Port
    itself (we may not want a full Port object just to price a series).

    Args:
        tariff_json_path: Path to a tariff JSON (default_tariff.json or one
            generated by tariff_seasonal.generate_tariff_json).

    Returns:
        A function timestamp: datetime -> float (EUR/kWh).
    """
    with open(tariff_json_path, "r", encoding="utf-8") as f:
        tariff_data = json.load(f)

    def price_fn(timestamp: datetime) -> float:
        day_key = str(timestamp.weekday())
        if day_key not in tariff_data.get("tariff", {}):
            return 0.0
        day_pricing = tariff_data["tariff"][day_key]["pricing"]
        rounded_minute = (timestamp.minute // 15) * 15
        time_str = f"{timestamp.hour:02d}:{rounded_minute:02d}"
        return day_pricing.get(time_str, 0.0)

    return price_fn


def compute_grid_energy_cost(
    db_manager: DatabaseManager,
    grid_source_name: str,
    tariff_json_path: str,
) -> List[Tuple[str, float]]:
    """
    Compute grid_energy_cost (EUR) per timestep, for one source's logged
    power_active_import measurements.

    Args:
        db_manager: DatabaseManager pointed at the run's database.
        grid_source_name: source_name of the port/grid connection point as
            logged by PyPort (e.g. the port's own name).
        tariff_json_path: Tariff JSON to price against (pick the seasonal
            one matching the run's dates via tariff_seasonal.get_seasonal_tariff_path).

    Returns:
        List of (timestamp, cost_eur) tuples, one per measurement row.
    """
    price_fn = load_tariff_price_fn(tariff_json_path)

    source = db_manager.get_source(source_name=grid_source_name)
    if source is None:
        raise ValueError(f"No source named '{grid_source_name}' found")

    metric_id = db_manager.get_metric_id("power_active_import")
    rows = db_manager.get_records(
        "measurements", source_id=source["source_id"], metric_id=metric_id
    )

    if len(rows) < 2:
        return []

    results = []
    prev_row = rows[0]
    for row in rows[1:]:
        t_prev = datetime.fromisoformat(prev_row["timestamp"])
        t_curr = datetime.fromisoformat(row["timestamp"])
        dt_hours = (t_curr - t_prev).total_seconds() / 3600.0
        power_kw = float(prev_row["value"])
        price = price_fn(t_prev)
        cost_eur = power_kw * dt_hours * price
        results.append((prev_row["timestamp"], cost_eur))
        prev_row = row

    return results


def save_economic_series(
    db_manager: DatabaseManager,
    metric_name: str,
    series: List[Tuple[str, float]],
    source_name: str = "economics_layer",
) -> None:
    """Write a (timestamp, value) series into `measurements` under a new economics_layer source."""
    source_id = db_manager.get_or_create_source(source_name, "economics")
    metric_id = db_manager.get_metric_id(metric_name)
    records = [(ts, source_id, metric_id, str(value)) for ts, value in series]
    db_manager.save_records_batch("measurements", records)


def main():
    parser = argparse.ArgumentParser(description="Compute economic KPIs for a PyPort run")
    parser.add_argument("--db", required=True, help="Path to the run's SQLite database")
    parser.add_argument("--grid-source", required=True, help="Source name of the grid connection (e.g. port name)")
    parser.add_argument("--tariff-json", required=True, help="Tariff JSON to price grid import against")
    args = parser.parse_args()

    if not Path(args.db).exists():
        raise SystemExit(f"Database not found: {args.db}")

    db_manager = DatabaseManager(args.db)
    register_economic_metrics(db_manager)

    cost_series = compute_grid_energy_cost(db_manager, args.grid_source, args.tariff_json)
    save_economic_series(db_manager, "grid_energy_cost", cost_series)

    total_cost = sum(v for _, v in cost_series)
    print(f"Grid energy cost written: {len(cost_series)} timesteps, total = EUR {total_cost:.2f}")


if __name__ == "__main__":
    main()